"""Add scraper models

Revision ID: 0d3f641c736e
Revises: 99e44520464e
Create Date: 2026-08-18 23:27:59.217042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3f641c736e'
down_revision: Union[str, None] = '99e44520464e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_health',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('collector_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_health_collector_id'), 'scraper_health', ['collector_id'], unique=True)
    op.create_index(op.f('ix_scraper_health_company_id'), 'scraper_health', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraper_health_company_id'), table_name='scraper_health')
    op.drop_index(op.f('ix_scraper_health_collector_id'), table_name='scraper_health')
    op.drop_table('scraper_health')
    # ### end Alembic commands ###
