"""Add genome models

Revision ID: 864bbf0342a0
Revises: f2fccc4c2a20
Create Date: 2026-08-18 23:19:27.500280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864bbf0342a0'
down_revision: Union[str, None] = 'f2fccc4c2a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genome_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('sequence_job_id', sa.String(), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['sequence_job_id'], ['sequence_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genome_snapshots_company_id'), 'genome_snapshots', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genome_snapshots_company_id'), table_name='genome_snapshots')
    op.drop_table('genome_snapshots')
    # ### end Alembic commands ###
