"""Add agent models

Revision ID: 99e44520464e
Revises: eb53b383e041
Create Date: 2026-08-18 23:25:05.560203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e44520464e'
down_revision: Union[str, None] = 'eb53b383e041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('mutation_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('final_result', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['mutation_id'], ['mutations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_company_id'), 'agent_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_mutation_id'), 'agent_runs', ['mutation_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('input_summary', sa.String(), nullable=True),
    sa.Column('output_summary', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_agent_run_id'), 'agent_events', ['agent_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_events_agent_run_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_agent_runs_mutation_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_company_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
