"""Add mutation models

Revision ID: eb53b383e041
Revises: 864bbf0342a0
Create Date: 2026-08-18 23:21:47.929158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb53b383e041'
down_revision: Union[str, None] = '864bbf0342a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('sequence_job_id', sa.String(), nullable=True),
    sa.Column('trait', sa.String(), nullable=True),
    sa.Column('old_value', sa.Float(), nullable=True),
    sa.Column('new_value', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('percentage_change', sa.Float(), nullable=True),
    sa.Column('mutation_type', sa.String(), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('investigation_status', sa.String(), nullable=True),
    sa.Column('final_explanation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['sequence_job_id'], ['sequence_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mutations_company_id'), 'mutations', ['company_id'], unique=False)
    op.create_index(op.f('ix_mutations_trait'), 'mutations', ['trait'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutations_trait'), table_name='mutations')
    op.drop_index(op.f('ix_mutations_company_id'), table_name='mutations')
    op.drop_table('mutations')
    # ### end Alembic commands ###
