"""Add evidence model

Revision ID: f2fccc4c2a20
Revises: 496fd211a631
Create Date: 2026-08-18 21:58:44.233370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fccc4c2a20'
down_revision: Union[str, None] = '496fd211a631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('trait', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['raw_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_company_id'), 'evidence', ['company_id'], unique=False)
    op.create_index(op.f('ix_evidence_trait'), 'evidence', ['trait'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_trait'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_company_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
