from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc
from app.db.models.genome_models import GenomeSnapshot
from app.db.models.mutation_models import MutationCandidate
from app.db.models.evidence_models import Evidence
from app.genome.comparator import compare_genomes
import logging

logger = logging.getLogger(__name__)

async def detect_mutations_for_company(company_id: str, job_id: str, current_genome: GenomeSnapshot, db: AsyncSession) -> list[MutationCandidate]:
    """
    Detects mutations by comparing the current genome to the previous genome.
    """
    logger.info(f"Detecting mutations for company {company_id} (Job: {job_id})")
    
    # Retrieve the previous genome (the one right before the current one)
    result = await db.execute(
        select(GenomeSnapshot)
        .where(GenomeSnapshot.company_id == company_id)
        .where(GenomeSnapshot.id != current_genome.id)
        .order_by(desc(GenomeSnapshot.created_at))
        .limit(1)
    )
    previous_genome = result.scalar_one_or_none()
    
    if not previous_genome:
        logger.info("No previous genome found. Skipping mutation detection.")
        return []
        
    # We also need the recent evidence to link to the mutations
    # For MVP, grab evidence generated by this sequence job.
    # Since evidence doesn't have sequence_job_id directly, we match by snapshot's run_id or just get latest.
    # We will get all evidence for simplicity right now and filter in memory by recent timestamps.
    ev_result = await db.execute(
        select(Evidence).where(Evidence.company_id == company_id)
    )
    all_evidence = ev_result.scalars().all()
    # Mocking 'recent' evidence as all evidence for the MVP since we overwrite or append during local runs.
    
    mutations = compare_genomes(previous_genome, current_genome, job_id, all_evidence)
    
    for mutation in mutations:
        db.add(mutation)
        
    await db.commit()
    logger.info(f"Generated {len(mutations)} mutation candidates.")
    return mutations
